from microservices.rendering_services.video_builder.clip_templates.TitleClip import TitleClip
from microservices.rendering_services.video_builder.clip_templates.EndClip import EndClip
from microservices.rendering_services.video_builder.clip_templates.TextClip import TextClip
from microservices.rendering_services.video_builder.clip_templates.ImageClip import ImageClip
from microservices.rendering_services.video_builder.clip_templates.ScrollingTextClip import ScrollingTextClip
from microservices.rendering_services.video_builder.clip_templates.CoverClip import CoverClip